set nocompatible               " be iMproved
filetype off                   " required!

" Vundle configurations.
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" original repos on github
" ---------------------------------------------------------------------------
" Git wrapper for vim. Who needs git bash any more ;)
Bundle 'tpope/vim-fugitive'

" Navigate the document like a pro. Who needs a mouse any more ;)
Bundle 'Lokaltog/vim-easymotion'

" Opens a toolbar with method and class indexes
Bundle 'majutsushi/tagbar.git' 
" Enable Tags bar in the side
nmap <F8> :TagbarToggle<CR>

" Syntax Highlighter
Bundle 'scrooloose/syntastic.git'
let g:syntastic_check_on_open=1 " Enable syntax check when a file is opened or saved
nmap <F6> :SyntasticToggleMode<CR> " Toggle Syntax highlight

" Zen Coding. Expands HTML abbreviations. Need to decide between one of these
Bundle 'mattn/zencoding-vim.git' 
let g:use_zen_complete_tag = 1 " for tag auto complete.
" Similar to Zen coding. But uses <c-e> as shortcut
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}

" Automatically close tags, quotes etc
Bundle 'Raimondi/delimitMate'

" Show diff of the current file from scms. Who needs Tortoise svn any more ;)
Bundle 'sudar/vim-scmdiff.git'

" Smart find and replace
Bundle 'tpope/vim-abolish'

" Surround - Easily change, add and delete around surroundings
Bundle 'tpope/vim-surround'
" Key mappings
" Normal mode
"-----------
"ds  - delete a surrounding
"cs  - change a surrounding
"ys  - add a surrounding
"yS  - add a surrounding and place the surrounded text on a new line + indent it
"yss - add a surrounding to the whole line
"ySs - add a surrounding to the whole line, place it on a new line + indent it
"ySS - same as ySs

"Visual mode
"-----------
"s   - in visual mode, add a surrounding
"S   - in visual mode, add a surrounding but place text on new line + indent it

"Insert mode
"-----------
"<CTRL-s> - in insert mode, add a surrounding
"<CTRL-s><CTRL-s> - in insert mode, add a new line + surrounding + indent
"<CTRL-g>s - same as <CTRL-s>
"<CTRL-g>S - same as <CTRL-s><CTRL-s>

" ---------------------------------------------------------------------------
  
"  Repeat the last command. Press . to repeat the last command.
Bundle "tpope/vim-repeat"

" Snippet manager. When you get all Snippets, who needs Textmate anymore ;)
" Dependencies
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
" Additional snippets for snipmate
Bundle 'honza/snipmate-snippets'
" Add the main Plugin
Bundle 'garbas/vim-snipmate'

" ---------------------------------------------------------------------------
" Open an auto complete popup. Who needs an IDE anymore.
Bundle 'Shougo/neocomplcache'

" configurations. More configurations at https://github.com/Shougo/neocomplcache
let g:neocomplcache_enable_at_startup = 1
" Use smartcase.
let g:neocomplcache_enable_smart_case = 1
" Use camel case completion.
let g:neocomplcache_enable_camel_case_completion = 1
" Use underbar completion.
let g:neocomplcache_enable_underbar_completion = 1
" Set minimum syntax keyword length.
let g:neocomplcache_min_syntax_length = 3
let g:neocomplcache_lock_buffer_name_pattern = '\*ku\*'

" Recommended key-mappings.
" <CR>: close popup and save indent.
inoremap <expr><CR>  neocomplcache#smart_close_popup() . "\<CR>"
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplcache#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplcache#smart_close_popup()."\<C-h>"
inoremap <expr><C-y>  neocomplcache#close_popup()
inoremap <expr><C-e>  neocomplcache#cancel_popup()

" Additional Mapping
inoremap <expr> <Esc>      pumvisible() ? "\<C-e>" : "\<Esc>"
inoremap <expr> <CR>       pumvisible() ? "\<C-y>" : "\<CR>"
inoremap <expr> <Down>     pumvisible() ? "\<C-n>" : "\<Down>"
inoremap <expr> <Up>       pumvisible() ? "\<C-p>" : "\<Up>"
inoremap <expr> <PageDown> pumvisible() ? "\<PageDown>\<C-p>\<C-n>" : "\<PageDown>"
inoremap <expr> <PageUp>   pumvisible() ? "\<PageUp>\<C-p>\<C-n>" : "\<PageUp>"

" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Enable heavy omni completion.
if !exists('g:neocomplcache_omni_patterns')
  let g:neocomplcache_omni_patterns = {}
endif
let g:neocomplcache_omni_patterns.php = '[^. \t]->\h\w*\|\h\w*::'
let g:neocomplcache_omni_patterns.c = '\%(\.\|->\)\h\w*'
let g:neocomplcache_omni_patterns.cpp = '\h\w*\%(\.\|->\)\h\w*\|\h\w*::'

" Use tab for completion
Bundle 'ervandew/supertab'

" vim-scripts repos
" ---------------------------------------------------------------------------

" Makes searching easier
Bundle 'L9'
Bundle 'FuzzyFinder'

" Has a smart status line
Bundle 'SmartusLine' 

" Automatically match tags and braces in different files. 
Bundle 'matchit.zip'
" Python match support
Bundle 'python_match.vim'

" Tag generation and syntax highlights
Bundle 'easytags.vim'

" Bulk (Un)Comment line. 
Bundle 'comments.vim'

" Smart yanking
Bundle 'YankRing.vim'

" Color Parenthsis in multiple colors 
Bundle 'Rainbow-Parenthsis-Bundle'

" non github repos
" ---------------------------------------------------------------------------
" Shows the list of files in the current directory. Who needs. Textmate any more ;)
" Make sure you have ruby mappings enabled in Vim and compile the C extension
" after installing this Plugin
Bundle 'git://git.wincent.com/command-t.git'
" Command T mappings. Who needs Textmate anymore ;)
nnoremap <silent> <Leader>t :CommandT<CR>
nnoremap <silent> <Leader>b :CommandTBuffer<CR>

" Color Schemes
" ---------------------------------------------------------------------------

" Color Schemes explorer. Browse through the different color schmes
Bundle 'Color-Scheme-Explorer'

" Programmer Color scheme
Bundle 'pw' 

" Light ColorScheme
Bundle 'lightdiff'

" 256 color schemes
Bundle 'Eddie.vim'
Bundle 'desert256.vim'
Bundle 'ciaranm/inkpot'
Bundle '256-grayvim'

" Set the default color scheme
colorscheme desert256

" color schemes
if &t_Co >= 256 || has("gui_running")
   colorscheme desert 
endif

" Show diff of changes that have been made after the file has been opened
if !exists(":DiffOrig")
	command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
             \ | wincmd p | diffthis
endif

" ---------------------------------------------------------------------------
" Common settings

set hidden		  " Hides buffer instead of closing them

set tabstop=4     " a tab is four spaces
set shiftwidth=4  " number of spaces to use for autoindenting
set softtabstop=4
set expandtab
set nowrap        " don't wrap lines

set backspace=indent,eol,start " allow backspacing over everything in insert mode
set autoindent    " always set auto indenting on
set copyindent    " copy the previous indentation on autoindenting
set number        " always show line numbers

set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'
set showmatch     " set show matching parenthesis
set smarttab      " insert tabs on the start of a line according to shiftwidth, not tabstop

" Set to auto read when a file is changed from the outside
set autoread

" History related settings
set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo

set title                " change the terminal's title
set visualbell           " don't beep
set noerrorbells         " don't beep

set nobackup
set noswapfile
set wildignore=*.swp,*.bak,*.pyc,*.class

" Search related settings
set ignorecase    " ignore case when searching
set smartcase     " ignore case if search pattern is all lowercase,case-sensitive otherwise
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type
set gdefault	  " Make search/replace global

" Clear highlighted searches
nmap <silent> ,/ :nohlsearch<CR>

" Use Tab for moving to next matching tag
nnoremap <tab> %
vnoremap <tab> %

" Enable automatic spell correction
set spell

" Enable Mouse
set mouse=a

" Highlight current line and column
au WinLeave * set nocursorline " nocursorcolumn
au WinEnter * set cursorline " cursorcolumn
set cursorline " cursorcolumn

" Command Mode settings
" ----------------------------------------------------------------------------

" Bash like keys for the command line
cnoremap <C-A>      <Home>
cnoremap <C-E>      <End>
cnoremap <C-K>      <C-U>

cnoremap <C-P> <Up>
cnoremap <C-N> <Down>

" This shows what you are typing as a command.  I love this!
set showcmd

" ----------------------------------------------------------------------------
" Key mappings
" ------------
"  
" Paste without messing up formatting.
set pastetoggle=<F2>

"Select previously pasted text for quick formatting.
nnoremap <leader>v V`]

" change the mapleader from \ to ,
let mapleader=","

" Map ; to : so that you can save pressing shift
nnoremap ; :

" forgot sudo while opening the file
cmap w!! w !sudo tee % >/dev/null

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" Mapping for tabs
nmap <silent> <Leader>h :tabp<CR>
nmap <silent> <Leader>l :tabn<CR>
nmap <leader>1 1gt
nmap <leader>2 2gt
nmap <leader>3 3gt
nmap <leader>4 4gt
nmap <leader>5 5gt
nmap <leader>6 6gt
nmap <leader>7 7gt
nmap <leader>8 8gt
nmap <leader>9 9gt
nmap <leader>0 10gt

" Easy window navigation. Prevents another keypress.
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Use Q for formatting the current paragraph (or selection)
vmap Q gq
nmap Q gqap

" Escape insert mode without pressing esc
:imap jj <Esc>

" Create Blank Newlines and stay in Normal mode
nnoremap <silent> zj o<Esc>
nnoremap <silent> zk O<Esc>

" Map F1 key to Esc. Would be interested in those situations where you hit f1 by default
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

"Move a line of text using ALT+[jk] 
nmap <M-j> mz:m+<cr>`z
nmap <M-k> mz:m-2<cr>`z
vmap <M-j> :m'>+<cr>`<my`>mzgv`yo`z
vmap <M-k> :m'<-2<cr>`>my`<mzgv`yo`z

" File type specific settings
filetype plugin indent on

" -------- HTML/CSS -----------------------
"Fold HTML Tag
nnoremap <leader>ft Vatzf

"Sort CSS properties
nnoremap <leader>S ?{<CR>jV/^\s*\}?$<CR>k:sort<CR>:noh<CR>

" -------- Python -----------------------
autocmd filetype python set expandtab

if &t_Co > 2 || has("gui_running")
   	" switch syntax highlighting on, when the terminal has colors
    syntax on
endif
