# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias free="free -m"

# exclude .svn and .git while doing grep
alias grepe='grep --exclude-dir=".svn" --exclude-dir=".git"'

# color svn diff. Make sure colordiff is installed
alias svnd="svn diff | colordiff | less -R"
function svndiff () { svn diff $@ | colordiff | less -R; }
alias gitd="git diff --color"

alias devsvn='find . -name ".svn" -type d -exec rm -rf {} \;'

# add more to cat command
cat()
{
   /bin/cat "$@" | more
}
